
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CASE DIFERENTE DIVISION DO ELSE FOR IF IGUAL MAYOROIGUALQUE MAYORQUE MENOROIGUALQUE MENORQUE MULTIPLICACION NUMERO OR PARENTESISD PARENTESISI POTENCIA RESTA RESTO SUMA SWITCH WHILEexpression : expression AND termexpression : expression RESTA termexpression : termterm : term MULTIPLICACION factorterm : term DIVISION factorterm : factorfactor : NUMEROfactor : PARENTESISI expression PARENTESISDterm : term POTENCIA termterm : term RESTO termexpression : term MAYORQUE termexpression : term MENORQUE termexpression : term IGUAL termexpression : term MAYOROIGUALQUE termexpression : term MENOROIGUALQUE termexpression : term DIFERENTE term'
    
_lr_action_items = {'NUMERO':([0,5,6,7,8,9,10,11,12,13,14,15,16,17,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'PARENTESISI':([0,5,6,7,8,9,10,11,12,13,14,15,16,17,],[5,5,5,5,5,5,5,5,5,5,5,5,5,5,]),'$end':([1,2,3,4,19,20,21,22,23,24,25,26,27,28,29,30,31,],[0,-3,-6,-7,-1,-2,-11,-12,-13,-14,-15,-16,-4,-5,-9,-10,-8,]),'AND':([1,2,3,4,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[6,-3,-6,-7,6,-1,-2,-11,-12,-13,-14,-15,-16,-4,-5,-9,-10,-8,]),'RESTA':([1,2,3,4,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[7,-3,-6,-7,7,-1,-2,-11,-12,-13,-14,-15,-16,-4,-5,-9,-10,-8,]),'PARENTESISD':([2,3,4,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[-3,-6,-7,31,-1,-2,-11,-12,-13,-14,-15,-16,-4,-5,-9,-10,-8,]),'MAYORQUE':([2,3,4,27,28,29,30,31,],[8,-6,-7,-4,-5,-9,-10,-8,]),'MENORQUE':([2,3,4,27,28,29,30,31,],[9,-6,-7,-4,-5,-9,-10,-8,]),'IGUAL':([2,3,4,27,28,29,30,31,],[10,-6,-7,-4,-5,-9,-10,-8,]),'MAYOROIGUALQUE':([2,3,4,27,28,29,30,31,],[11,-6,-7,-4,-5,-9,-10,-8,]),'MENOROIGUALQUE':([2,3,4,27,28,29,30,31,],[12,-6,-7,-4,-5,-9,-10,-8,]),'DIFERENTE':([2,3,4,27,28,29,30,31,],[13,-6,-7,-4,-5,-9,-10,-8,]),'MULTIPLICACION':([2,3,4,19,20,21,22,23,24,25,26,27,28,29,30,31,],[14,-6,-7,14,14,14,14,14,14,14,14,-4,-5,14,14,-8,]),'DIVISION':([2,3,4,19,20,21,22,23,24,25,26,27,28,29,30,31,],[15,-6,-7,15,15,15,15,15,15,15,15,-4,-5,15,15,-8,]),'POTENCIA':([2,3,4,19,20,21,22,23,24,25,26,27,28,29,30,31,],[16,-6,-7,16,16,16,16,16,16,16,16,-4,-5,16,16,-8,]),'RESTO':([2,3,4,19,20,21,22,23,24,25,26,27,28,29,30,31,],[17,-6,-7,17,17,17,17,17,17,17,17,-4,-5,17,17,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,18,]),'term':([0,5,6,7,8,9,10,11,12,13,16,17,],[2,2,19,20,21,22,23,24,25,26,29,30,]),'factor':([0,5,6,7,8,9,10,11,12,13,14,15,16,17,],[3,3,3,3,3,3,3,3,3,3,27,28,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND term','expression',3,'p_expression_plus','syntax.py',7),
  ('expression -> expression RESTA term','expression',3,'p_expression_minus','syntax.py',11),
  ('expression -> term','expression',1,'p_expression_term','syntax.py',15),
  ('term -> term MULTIPLICACION factor','term',3,'p_term_times','syntax.py',19),
  ('term -> term DIVISION factor','term',3,'p_term_div','syntax.py',23),
  ('term -> factor','term',1,'p_term_factor','syntax.py',27),
  ('factor -> NUMERO','factor',1,'p_factor_num','syntax.py',31),
  ('factor -> PARENTESISI expression PARENTESISD','factor',3,'p_factor_expr','syntax.py',35),
  ('term -> term POTENCIA term','term',3,'p_term_potencia','syntax.py',39),
  ('term -> term RESTO term','term',3,'p_term_modulo','syntax.py',43),
  ('expression -> term MAYORQUE term','expression',3,'p_expression_mayor','syntax.py',47),
  ('expression -> term MENORQUE term','expression',3,'p_expression_menor','syntax.py',51),
  ('expression -> term IGUAL term','expression',3,'p_expression_igual','syntax.py',55),
  ('expression -> term MAYOROIGUALQUE term','expression',3,'p_expression_mayorq','syntax.py',59),
  ('expression -> term MENOROIGUALQUE term','expression',3,'p_expression_menorq','syntax.py',63),
  ('expression -> term DIFERENTE term','expression',3,'p_expression_dif','syntax.py',67),
]
